### PR TITLE
Allow clear text communication also in Android 9 and above

### PR DESCRIPTION
**Pull request by b1zzu**
### Description

Starting with Android 9 clear text communication (http, ws) between the client app and the server is disabled by default.

Most of the user will start the ionic-showcase server locally without any tls certificate (https), and if then they deploy the android app to an android emulator or a real device with android 9 or greater they will have this error in the console `ERR_CLEARTEXT_NOT_PERMITTED`.

I would like to globally enable clear text communication in order to make it more simple to new users to try the ionic-showcase on all devices. 

An alternative solution to this problem is to document in the README how to globally enable clear text [1] or how to do it only for specific domains [2].

1. https://developer.android.com/training/articles/security-config#base-config
2. https://developer.android.com/training/articles/security-config#domain-config

##### Checklist

- [ ] `npm test` passes
- [ ] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
+1000 to do it. We have been talking about this for quite long time. 
Take look for cordova config that allow us to add plist file items for ios and elements to manifest on Android.

**Comment by b1zzu** [comment]
> +1000 to do it. We have been talking about this for quite long time.
> Take look for cordova config that allow us to add plist file items for ios and elements to manifest on Android.

Don't know how to do it for iOS but for Android, the network_security_config.xml is already copied [1] inside the app and enabled inside the AndroidManifest.xml [2]

1. https://github.com/aerogear/ionic-showcase/blob/7524c77e7ed5ab223316e53b1036954620ea61b6/config.xml#L42
2. https://github.com/aerogear/ionic-showcase/blob/7524c77e7ed5ab223316e53b1036954620ea61b6/config.xml#L44

**Comment by wtrocki** [comment]
It will require additional entry in plist file

```xml
<key>NSAppTransportSecurity</key>
<dict>
  <!--Include to allow all connections (DANGER)-->
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>
```

**Comment by wtrocki** [comment]
@b1zzu Any progress on this. I can merge it now for Android and we can get the IOS in separate PR?

**Comment by b1zzu** [comment]
@wtrocki I'm working on testing it on iOS

**Comment by b1zzu** [comment]
@wtrocki `NSAllowsArbitraryLoads` is already enabled by default: https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md#392-oct-30-2015 there is no need to add it to the config file

**Pull request merged**
