### PR TITLE
fix: use voyager-server 0.7.0

### PR DESCRIPTION
**Pull request by darahayes**
### Description

This PR uses a dev release of voyager-server. The purpose of this is to help verify the changes from https://github.com/aerogear/voyager-server/pull/192

### Happy Path

* Start up `docker-compose as normal`
* Start keycloak with `npm run keycloak`
* Init keycloak with `npm run keycloak:init`
* Follow instructions output from `keycloak:init` script to copy the appropriate keycloak configs into `mobile-services.json` and into `server/src/config/keycloak.json`
* Start server and App
* Verify you can log in (`developer/developer` or `admin/admin`) and access resources, verify subscriptions still work,

### `auth` and `hasRole` on subscriptions

* in `server/src/tasks/subscriptions.js` try out the new `hasRole` and `auth` resolver middlewares exported by `voyager-keycloak`

```
const { hasRole } = require('@aerogear/voyager-keycloak`)
```

and in the subscription resolvers

```
const subscriptionResolvers = {
  Subscription: {
    taskAdded: {
      subscribe: hasRole('developer')(() => pubSub.asyncIterator(TASK_ADDED))
    },
    taskDeleted: {
      subscribe: () => pubSub.asyncIterator(TASK_DELETED)
    },
    taskUpdated: {
      subscribe: () => pubSub.asyncIterator(TASK_UPDATED)
    }
  },
}
```

^^ Subscriptions should still work for the `developer` user.

Now change the `hasRole` value to something different.

In chrome devtools you should see the websocket connection to the `/graphql` endpoint failing.

Screenshot 2019-07-15 at 16 04 43

## @auth and @hasRole directives

You will need to modify this line https://github.com/aerogear/ionic-showcase/blob/master/server/src/index.js#L51 to include the keycloak typeDefs:

```
typeDefs: [keycloakService.getTypeDefs() , appTypeDefs],
```

Now you can apply `hasRole` and `auth` (auth doesn't really make sense because we have auth applied to the entire graphql endpoint) on various things on the schema.

By default the `developer` user has a role of `developer` and the admin user has a role `admin`

##### Checklist

- [ ] `npm test` passes
- [ ] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
👀

**Comment by wtrocki** [comment]
> Follow instructions output from keycloak:init script to copy the appropriate keycloak configs into mobile-services.json and into server/src/config/keycloak.json


This is awesome! I would be uber awesome if we path those automatically basing on relative paths.

**Comment by wtrocki** [comment]
> in server/src/tasks/subscriptions.js try out the new hasRole and auth resolver middlewares exported by voyager-keycloak

I like it but is there any reason why we do not showcase this in showcase. 
Everything new should be there. Auth service has flag to detect if service is enabled

**Comment by wtrocki** [comment]
With tons of automation, our keycloak setup is now so easy and fast. Good work!

**Comment by darahayes** [comment]
@wtrocki I'm kinda -1 on putting those configs there automatically because it will upset yourself and @StephenCoady's development flow. It means that you run that script once and now you have to manually delete those files any time you want to run without keycloak again. I did that in a way that it helps keep the keycloak stuff out of the way as much as possible, unless you really want it there.

**Comment by darahayes** [comment]
During my testing, I discovered an issue in the underlying keycloak-connect-graphql library that kinda breaks `hasRole` for subscriptions. Basically, `hasRole` for subscriptions would check if the user has a keycloak client role, in the frontend public client, whereas `hasRole` in the regular resolvers would check against the server's client. (Bearer client). Checking against the client that the server uses seems to be the correct approach. (That's what `keycloak.protect` does)

I've created a PR here: to fix that issue: https://github.com/aerogear/keycloak-connect-graphql/pull/23

**Comment by darahayes** [comment]
> I like it but is there any reason why we do not showcase this in showcase.

It didn't exist before. I would be happy to optionally add kecyloak stuff in there but then it will require lots of boilerplate to ensure that the correct schema/resolvers are used depending on whether keycloak is enabled. (We have to be careful not to break the happy path non keycloak demo flow)

**Comment by wtrocki** [comment]
> It didn't exist before. I would be happy to optionally add kecyloak stuff in there but then it will require lots of boilerplate to ensure that the correct schema/resolvers are used depending on whether keycloak is enabled. (We have to be careful not to break the happy path non keycloak demo flow)

Ok Agreed.

**Pull request merged**
