### PR TITLE
Data Sync prototype on top of Offix and Graphback

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Make showcase work with mongo (we added some hacks around _id/id formatting mostly by saving both) When more time we can figure out proper mapping. 

Current change is introducing new Connection interface and also saves and restores delta from separate table. There are couple TODO's here. 

Currently this works 100% on server but we will need to build custom cache updates on the client to make this work end to end.

# How to

Follow readme for server - it will run mongo instead of postgress.

Open Playground and execute queries and mutations. Check the data in db.
Also experiment with last updated (it will deliver delta that can be applied to client). On client we need to know only delete the information as the rest will be automatically merged into existing cache functions.

### CODE REVIEW

**Comment by wtrocki** [comment]
CC @darahayes

**Comment by deewhyweb** [comment]
Just spun up this version.  I can see the collection being created in mongoDB, tasks_delta.
I created a new task, this appeared in the tasks_delta table immediately.

When I make an update though, it seems to be out of step.
e.g. I edited the title from "2nd test" to "2nd test edit" 
When I click on update, the task still shows as "2nd test"

When I edit again, this time to "2nd test again", when I click on update the task is now called "2nd test edit", and I can see this record appearing in mongo.

**Comment by deewhyweb** [comment]
I tried deleting a task.  It went immediately from the client and I could see the document in task_delta with the flag _deleted set to true; so I can see how this will work.

**Comment by deewhyweb** [comment]
It doesn't look like the version value is getting updated when I make changes to tasks

**Comment by wtrocki** [comment]
Generally there could be couple bugs here. There is no support for this on client at the moment but we will add that tomorrow

I have removed versioning to simplify resolver logic so it will be possible to copy it. I can add it if needed.

**Comment by wtrocki** [comment]
Fixed those issues.

**Comment by deewhyweb** [comment]
Versioning is not something we require for our current engagement

**Comment by deewhyweb** [comment]
I notice the tasks collection also has a _deleted flag, is this necessary?
In our environment, the resolver calls a service via a restful call (the data is in mongo on this service).    We'd prefer not to have to add additional flags to this data.

**Comment by wtrocki** [comment]
Original collection should stay unchanged in the whole process. I have added some extra fields when experimenting with data

**Comment by wtrocki** [comment]
We have changed the architecture to make things simple. As we no longer need conflict resolution on the server we have decided to not store diff at all. 
We are going to store duplicates of original data into metadata table that will contain additional information about soft deletes. this will minimize amount of processing on client and server and simplify entire example

**Comment by wtrocki** [comment]
What is outstanding now is to:

- Provide custom update functions on the client that will use `deleted` field as marker to remove items from cache. 

- Make `lastSync` information available globally for each type.

- Create helper to perform sync for specific types when network is restored.

**Comment by darahayes** [comment]
Quick update:

I've added a really rough implementation for performing the sync query.

I've added an additional sync button to the top right corner of the UI that lets you manually perform the sync query.

Screenshot 2020-01-24 at 16 58 27

Subscriptions and mutations are still broken in the app but you can test the sync query as follows.

1. Wipe the MongoDB instance
2. Open the Graphql Playground and create a couple of items (give them unique names to make things more understandable)
3. refresh the showcase app (every time you hit refresh it does a global refresh of the latest data)
4. back in the playground try to add new items, delete and/or update existing items and take note of which ones you deleted. 
5. In the playground perform the `allTasks` query with no `lastSync` variable to get the latest data in the playground
6. In the application open the network tab in dev tools.
7. Click the sync button and verify that the UI now shows the latest data
8. check the graphql request that was sent in the network tab and verify it only returned the updates since the last request.

**Comment by wtrocki** [comment]
What is outstanding is to make mutation and subscription updates available for this dataset.

**Comment by wtrocki** [comment]
Closing and linking to trello

**Pull request closed without merging**
