### PR TITLE
fix: issue where refreshing pwa causes 404

### PR DESCRIPTION
**Pull request by darahayes**
### Description

Fixes the problem where refreshing any non index page (e.g. tasks page) gives a 404 error.

##### Checklist

- [ ] `npm test` passes
- [ ] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
Requires changing router to https://angular.io/api/common/HashLocationStrategy

**Comment by wtrocki** [comment]
This breaks file integration on client. Let's use hash strategy in app.

**Comment by darahayes** [comment]
File upload is working fine for me. Have you tried it?

**Comment by wtrocki** [comment]
Issue on my side. Good to go!

**Pull request merged**
